export enum APP_SCREEN {
  HOME = 'HOME',
  CARD_ROTATE = 'CARD_ROTATE',
  SPACE_BUTTON = 'SPACE_BUTTON',
  CARD_GRADIENT = 'CARD_GRADIENT',
  MOUNTED_ELEMENT = 'MOUNTED_ELEMENT',
  SENSOR_WALLPAPER = 'SENSOR_WALLPAPER',
  SWIPE_SORT = 'SWIPE_SORT',
  CARD_3D = 'CARD_3D',
  REFRESH_ISLAND = 'REFRESH_ISLAND',
  COLOR_FILTER = 'COLOR_FILTER',
  SCRATCH_TICKET = 'SCRATCH_TICKET',
  TELEGRAM_LOCK = 'TELEGRAM_LOCK',
}

export type RootStackParamList = {
  [APP_SCREEN.HOME]: undefined;
  [APP_SCREEN.CARD_ROTATE]: undefined;
  [APP_SCREEN.CARD_GRADIENT]: undefined;
  [APP_SCREEN.SPACE_BUTTON]: undefined;
  [APP_SCREEN.MOUNTED_ELEMENT]: undefined;
  [APP_SCREEN.SENSOR_WALLPAPER]: undefined;
  [APP_SCREEN.SWIPE_SORT]: undefined;
  [APP_SCREEN.CARD_3D]: undefined;
  [APP_SCREEN.REFRESH_ISLAND]: undefined;
  [APP_SCREEN.COLOR_FILTER]: undefined;
  [APP_SCREEN.SCRATCH_TICKET]: undefined;
  [APP_SCREEN.TELEGRAM_LOCK]: undefined;
};
