export enum APP_SCREEN {
  HOME = 'HOME',
  CARD_ROTATE = 'CARD_ROTATE',
  SPACE_BUTTON = 'SPACE_BUTTON',
  CARD_GRADIENT = 'CARD_GRADIENT',
  MOUNTED_ELEMENT = 'MOUNTED_ELEMENT',
  SENSOR_WALLPAPER = 'SENSOR_WALLPAPER',
  SWIPE_SORT = 'SWIPE_SORT',
}

export type RootStackParamList = {
  [APP_SCREEN.HOME]: undefined;
  [APP_SCREEN.CARD_ROTATE]: undefined;
  [APP_SCREEN.CARD_GRADIENT]: undefined;
  [APP_SCREEN.SPACE_BUTTON]: undefined;
  [APP_SCREEN.MOUNTED_ELEMENT]: undefined;
  [APP_SCREEN.SENSOR_WALLPAPER]: undefined;
  [APP_SCREEN.SWIPE_SORT]: undefined;
};
