import {SkImage} from '@shopify/react-native-skia';
import {StackScreenProps as RNStackScreenProps} from '@react-navigation/stack';

export enum APP_SCREEN {
  HOME = 'HOME',
  CARD_ROTATE = 'CARD_ROTATE',
  SPACE_BUTTON = 'SPACE_BUTTON',
  CARD_GRADIENT = 'CARD_GRADIENT',
  MOUNTED_ELEMENT = 'MOUNTED_ELEMENT',
  SENSOR_WALLPAPER = 'SENSOR_WALLPAPER',
  SWIPE_SORT = 'SWIPE_SORT',
  CARD_3D = 'CARD_3D',
  REFRESH_ISLAND = 'REFRESH_ISLAND',
  COLOR_FILTER = 'COLOR_FILTER',
  SCRATCH_TICKET = 'SCRATCH_TICKET',
  TELEGRAM_LOCK = 'TELEGRAM_LOCK',
  ICON_MASK_TRANSITION = 'ICON_MASK_TRANSITION',
  LIKE_BUTTON = 'LIKE_BUTTON',
  INFINITY_DOT = 'INFINITY_DOT',
  LINE_CHART = 'LINE_CHART',
  PIE_CHART = 'PIE_CHART',
  TIKTOK_REMIX = 'TIKTOK_REMIX',
  ADN = 'ADN',
  DARK_LIGHT_MODE = 'DARK_LIGHT_MODE',
  GRID_ROTATE = 'GRID_ROTATE',
  IOS_APP_OPEN = 'IOS_APP_OPEN',
  DOTS_ANIMATION = 'DOTS_ANIMATION',
  LINE_GRAPH = 'LINE_GRAPH',
  GESTURE_FUNCTION = 'GESTURE_FUNCTION',
  CROP_IMAGE = 'CROP_IMAGE',
  CROP_IMAGE_RESULT = 'CROP_IMAGE_RESULT',
  SOUND_WAVE = 'SOUND_WAVE',
}

export type RootStackParamList = {
  [APP_SCREEN.HOME]: undefined;
  [APP_SCREEN.CARD_ROTATE]: undefined;
  [APP_SCREEN.CARD_GRADIENT]: undefined;
  [APP_SCREEN.SPACE_BUTTON]: undefined;
  [APP_SCREEN.MOUNTED_ELEMENT]: undefined;
  [APP_SCREEN.SENSOR_WALLPAPER]: undefined;
  [APP_SCREEN.SWIPE_SORT]: undefined;
  [APP_SCREEN.CARD_3D]: undefined;
  [APP_SCREEN.REFRESH_ISLAND]: undefined;
  [APP_SCREEN.COLOR_FILTER]: undefined;
  [APP_SCREEN.SCRATCH_TICKET]: undefined;
  [APP_SCREEN.TELEGRAM_LOCK]: undefined;
  [APP_SCREEN.ICON_MASK_TRANSITION]: undefined;
  [APP_SCREEN.LIKE_BUTTON]: undefined;
  [APP_SCREEN.INFINITY_DOT]: undefined;
  [APP_SCREEN.LINE_CHART]: undefined;
  [APP_SCREEN.PIE_CHART]: undefined;
  [APP_SCREEN.TIKTOK_REMIX]: undefined;
  [APP_SCREEN.ADN]: undefined;
  [APP_SCREEN.DARK_LIGHT_MODE]: undefined;
  [APP_SCREEN.GRID_ROTATE]: undefined;
  [APP_SCREEN.IOS_APP_OPEN]: undefined;
  [APP_SCREEN.DOTS_ANIMATION]: undefined;
  [APP_SCREEN.LINE_GRAPH]: undefined;
  [APP_SCREEN.GESTURE_FUNCTION]: undefined;
  [APP_SCREEN.CROP_IMAGE_RESULT]: {
    image: SkImage;
    width: number;
    height: number;
  };
  [APP_SCREEN.CROP_IMAGE]: undefined;
  [APP_SCREEN.SOUND_WAVE]: undefined;
};
export type StackScreenProps<T extends keyof RootStackParamList> =
  RNStackScreenProps<RootStackParamList, T>;
